name: Bug Report
description: Report a bug in canopy
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What did you do?
      placeholder: |
        1. Run `cn create ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: cn-version
    attributes:
      label: cn version
      description: Output of `cn --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun version
      description: Output of `bun --version`
      placeholder: "1.2.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 15, Ubuntu 22.04, Windows 11, etc."
    validations:
      required: true
